credentials:
  usernames:
    anio:
      email: aniowang@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Anio Wang
      password: anio1021 # Will be hashed automatically      
    test:
      email: test@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: test
      password: test123 # Will be hashed automatically

cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
  - melsby@gmail.com